# version: "3.9"
services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: sh -c "npm install && npm run dev"

  backend:
    build: ./backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=roamory_db
      - DB_USERNAME=roamory_user
      - DB_PASSWORD=roamory_pass
    depends_on:
      - db
    working_dir: /var/www/html
    command: sh -c "composer install && php artisan serve --host=0.0.0.0 --port=8000"

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: roamory_db
      POSTGRES_USER: roamory_user
      POSTGRES_PASSWORD: roamory_pass
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
