<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class CountriesTableSeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            ['code' => 'AF', 'name_ja' => 'アフガニスタン', 'name_en' => 'Afghanistan'],
            ['code' => 'AX', 'name_ja' => 'オーランド諸島', 'name_en' => 'Åland Islands'],
            ['code' => 'AL', 'name_ja' => 'アルバニア', 'name_en' => 'Albania'],
            ['code' => 'DZ', 'name_ja' => 'アルジェリア', 'name_en' => 'Algeria'],
            ['code' => 'AS', 'name_ja' => 'アメリカ領サモア', 'name_en' => 'American Samoa'],
            ['code' => 'AD', 'name_ja' => 'アンドラ', 'name_en' => 'Andorra'],
            ['code' => 'AO', 'name_ja' => 'アンゴラ', 'name_en' => 'Angola'],
            ['code' => 'AI', 'name_ja' => 'アンギラ', 'name_en' => 'Anguilla'],
            ['code' => 'AQ', 'name_ja' => '南極', 'name_en' => 'Antarctica'],
            ['code' => 'AG', 'name_ja' => 'アンティグア・バーブーダ', 'name_en' => 'Antigua and Barbuda'],
            ['code' => 'AR', 'name_ja' => 'アルゼンチン', 'name_en' => 'Argentina'],
            ['code' => 'AM', 'name_ja' => 'アルメニア', 'name_en' => 'Armenia'],
            ['code' => 'AW', 'name_ja' => 'アルバ', 'name_en' => 'Aruba'],
            ['code' => 'AU', 'name_ja' => 'オーストラリア', 'name_en' => 'Australia'],
            ['code' => 'AT', 'name_ja' => 'オーストリア', 'name_en' => 'Austria'],
            ['code' => 'AZ', 'name_ja' => 'アゼルバイジャン', 'name_en' => 'Azerbaijan'],
            ['code' => 'BS', 'name_ja' => 'バハマ', 'name_en' => 'Bahamas'],
            ['code' => 'BH', 'name_ja' => 'バーレーン', 'name_en' => 'Bahrain'],
            ['code' => 'BD', 'name_ja' => 'バングラデシュ', 'name_en' => 'Bangladesh'],
            ['code' => 'BB', 'name_ja' => 'バルバドス', 'name_en' => 'Barbados'],
            ['code' => 'BY', 'name_ja' => 'ベラルーシ', 'name_en' => 'Belarus'],
            ['code' => 'BE', 'name_ja' => 'ベルギー', 'name_en' => 'Belgium'],
            ['code' => 'BZ', 'name_ja' => 'ベリーズ', 'name_en' => 'Belize'],
            ['code' => 'BJ', 'name_ja' => 'ベナン', 'name_en' => 'Benin'],
            ['code' => 'BM', 'name_ja' => 'バミューダ', 'name_en' => 'Bermuda'],
            ['code' => 'BT', 'name_ja' => 'ブータン', 'name_en' => 'Bhutan'],
            ['code' => 'BO', 'name_ja' => 'ボリビア多民族国', 'name_en' => 'Bolivia (Plurinational State of)'],
            ['code' => 'BQ', 'name_ja' => 'ボネール、シント・ユースタティウスおよびサバ', 'name_en' => 'Bonaire, Sint Eustatius and Saba'],
            ['code' => 'BA', 'name_ja' => 'ボスニア・ヘルツェゴビナ', 'name_en' => 'Bosnia and Herzegovina'],
            ['code' => 'BW', 'name_ja' => 'ボツワナ', 'name_en' => 'Botswana'],
            ['code' => 'BV', 'name_ja' => 'ブーベ島', 'name_en' => 'Bouvet Island'],
            ['code' => 'BR', 'name_ja' => 'ブラジル', 'name_en' => 'Brazil'],
            ['code' => 'IO', 'name_ja' => 'イギリス領インド洋地域', 'name_en' => 'British Indian Ocean Territory'],
            ['code' => 'BN', 'name_ja' => 'ブルネイ・ダルサラーム', 'name_en' => 'Brunei Darussalam'],
            ['code' => 'BG', 'name_ja' => 'ブルガリア', 'name_en' => 'Bulgaria'],
            ['code' => 'BF', 'name_ja' => 'ブルキナファソ', 'name_en' => 'Burkina Faso'],
            ['code' => 'BI', 'name_ja' => 'ブルンジ', 'name_en' => 'Burundi'],
            ['code' => 'CV', 'name_ja' => 'カーボベルデ', 'name_en' => 'Cabo Verde'],
            ['code' => 'KH', 'name_ja' => 'カンボジア', 'name_en' => 'Cambodia'],
            ['code' => 'CM', 'name_ja' => 'カメルーン', 'name_en' => 'Cameroon'],
            ['code' => 'CA', 'name_ja' => 'カナダ', 'name_en' => 'Canada'],
            ['code' => 'KY', 'name_ja' => 'ケイマン諸島', 'name_en' => 'Cayman Islands'],
            ['code' => 'CF', 'name_ja' => '中央アフリカ共和国', 'name_en' => 'Central African Republic'],
            ['code' => 'TD', 'name_ja' => 'チャド', 'name_en' => 'Chad'],
            ['code' => 'CL', 'name_ja' => 'チリ', 'name_en' => 'Chile'],
            ['code' => 'CN', 'name_ja' => '中国', 'name_en' => 'China'],
            ['code' => 'CX', 'name_ja' => 'クリスマス島', 'name_en' => 'Christmas Island'],
            ['code' => 'CC', 'name_ja' => 'ココス（キーリング）諸島', 'name_en' => 'Cocos (Keeling) Islands'],
            ['code' => 'CO', 'name_ja' => 'コロンビア', 'name_en' => 'Colombia'],
            ['code' => 'KM', 'name_ja' => 'コモロ', 'name_en' => 'Comoros'],
            ['code' => 'CG', 'name_ja' => 'コンゴ共和国', 'name_en' => 'Congo'],
            ['code' => 'CD', 'name_ja' => 'コンゴ民主共和国', 'name_en' => 'Congo, Democratic Republic of the'],
            ['code' => 'CK', 'name_ja' => 'クック諸島', 'name_en' => 'Cook Islands'],
            ['code' => 'CR', 'name_ja' => 'コスタリカ', 'name_en' => 'Costa Rica'],
            ['code' => 'CI', 'name_ja' => 'コートジボワール', 'name_en' => 'Côte d\'Ivoire'],
            ['code' => 'HR', 'name_ja' => 'クロアチア', 'name_en' => 'Croatia'],
            ['code' => 'CU', 'name_ja' => 'キューバ', 'name_en' => 'Cuba'],
            ['code' => 'CW', 'name_ja' => 'キュラソー', 'name_en' => 'Curaçao'],
            ['code' => 'CY', 'name_ja' => 'キプロス', 'name_en' => 'Cyprus'],
            ['code' => 'CZ', 'name_ja' => 'チェコ', 'name_en' => 'Czechia'],
            ['code' => 'DK', 'name_ja' => 'デンマーク', 'name_en' => 'Denmark'],
            ['code' => 'DJ', 'name_ja' => 'ジブチ', 'name_en' => 'Djibouti'],
            ['code' => 'DM', 'name_ja' => 'ドミニカ国', 'name_en' => 'Dominica'],
            ['code' => 'DO', 'name_ja' => 'ドミニカ共和国', 'name_en' => 'Dominican Republic'],
            ['code' => 'EC', 'name_ja' => 'エクアドル', 'name_en' => 'Ecuador'],
            ['code' => 'EG', 'name_ja' => 'エジプト', 'name_en' => 'Egypt'],
            ['code' => 'SV', 'name_ja' => 'エルサルバドル', 'name_en' => 'El Salvador'],
            ['code' => 'GQ', 'name_ja' => '赤道ギニア', 'name_en' => 'Equatorial Guinea'],
            ['code' => 'ER', 'name_ja' => 'エリトリア', 'name_en' => 'Eritrea'],
            ['code' => 'EE', 'name_ja' => 'エストニア', 'name_en' => 'Estonia'],
            ['code' => 'SZ', 'name_ja' => 'エスワティニ', 'name_en' => 'Eswatini'],
            ['code' => 'ET', 'name_ja' => 'エチオピア', 'name_en' => 'Ethiopia'],
            ['code' => 'FK', 'name_ja' => 'フォークランド諸島（マルビナス諸島）', 'name_en' => 'Falkland Islands (Malvinas)'],
            ['code' => 'FO', 'name_ja' => 'フェロー諸島', 'name_en' => 'Faroe Islands'],
            ['code' => 'FJ', 'name_ja' => 'フィジー', 'name_en' => 'Fiji'],
            ['code' => 'FI', 'name_ja' => 'フィンランド', 'name_en' => 'Finland'],
            ['code' => 'FR', 'name_ja' => 'フランス', 'name_en' => 'France'],
            ['code' => 'GF', 'name_ja' => 'フランス領ギアナ', 'name_en' => 'French Guiana'],
            ['code' => 'PF', 'name_ja' => 'フランス領ポリネシア', 'name_en' => 'French Polynesia'],
            ['code' => 'TF', 'name_ja' => 'フランス領南方・南極地域', 'name_en' => 'French Southern Territories'],
            ['code' => 'GA', 'name_ja' => 'ガボン', 'name_en' => 'Gabon'],
            ['code' => 'GM', 'name_ja' => 'ガンビア', 'name_en' => 'Gambia'],
            ['code' => 'GE', 'name_ja' => 'ジョージア', 'name_en' => 'Georgia'],
            ['code' => 'DE', 'name_ja' => 'ドイツ', 'name_en' => 'Germany'],
            ['code' => 'GH', 'name_ja' => 'ガーナ', 'name_en' => 'Ghana'],
            ['code' => 'GI', 'name_ja' => 'ジブラルタル', 'name_en' => 'Gibraltar'],
            ['code' => 'GR', 'name_ja' => 'ギリシャ', 'name_en' => 'Greece'],
            ['code' => 'GL', 'name_ja' => 'グリーンランド', 'name_en' => 'Greenland'],
            ['code' => 'GD', 'name_ja' => 'グレナダ', 'name_en' => 'Grenada'],
            ['code' => 'GP', 'name_ja' => 'グアドループ', 'name_en' => 'Guadeloupe'],
            ['code' => 'GU', 'name_ja' => 'グアム', 'name_en' => 'Guam'],
            ['code' => 'GT', 'name_ja' => 'グアテマラ', 'name_en' => 'Guatemala'],
            ['code' => 'GG', 'name_ja' => 'ガーンジー', 'name_en' => 'Guernsey'],
            ['code' => 'GN', 'name_ja' => 'ギニア', 'name_en' => 'Guinea'],
            ['code' => 'GW', 'name_ja' => 'ギニアビサウ', 'name_en' => 'Guinea-Bissau'],
            ['code' => 'GY', 'name_ja' => 'ガイアナ', 'name_en' => 'Guyana'],
            ['code' => 'HT', 'name_ja' => 'ハイチ', 'name_en' => 'Haiti'],
            ['code' => 'HM', 'name_ja' => 'ハード島とマクドナルド諸島', 'name_en' => 'Heard Island and McDonald Islands'],
            ['code' => 'VA', 'name_ja' => 'バチカン市国', 'name_en' => 'Holy See'],
            ['code' => 'HN', 'name_ja' => 'ホンジュラス', 'name_en' => 'Honduras'],
            ['code' => 'HK', 'name_ja' => '香港', 'name_en' => 'Hong Kong'],
            ['code' => 'HU', 'name_ja' => 'ハンガリー', 'name_en' => 'Hungary'],
            ['code' => 'IS', 'name_ja' => 'アイスランド', 'name_en' => 'Iceland'],
            ['code' => 'IN', 'name_ja' => 'インド', 'name_en' => 'India'],
            ['code' => 'ID', 'name_ja' => 'インドネシア', 'name_en' => 'Indonesia'],
            ['code' => 'IR', 'name_ja' => 'イラン・イスラム共和国', 'name_en' => 'Iran (Islamic Republic of)'],
            ['code' => 'IQ', 'name_ja' => 'イラク', 'name_en' => 'Iraq'],
            ['code' => 'IE', 'name_ja' => 'アイルランド', 'name_en' => 'Ireland'],
            ['code' => 'IM', 'name_ja' => 'マン島', 'name_en' => 'Isle of Man'],
            ['code' => 'IL', 'name_ja' => 'イスラエル', 'name_en' => 'Israel'],
            ['code' => 'IT', 'name_ja' => 'イタリア', 'name_en' => 'Italy'],
            ['code' => 'JM', 'name_ja' => 'ジャマイカ', 'name_en' => 'Jamaica'],
            ['code' => 'JP', 'name_ja' => '日本', 'name_en' => 'Japan'],
            ['code' => 'JE', 'name_ja' => 'ジャージー', 'name_en' => 'Jersey'],
            ['code' => 'JO', 'name_ja' => 'ヨルダン', 'name_en' => 'Jordan'],
            ['code' => 'KZ', 'name_ja' => 'カザフスタン', 'name_en' => 'Kazakhstan'],
            ['code' => 'KE', 'name_ja' => 'ケニア', 'name_en' => 'Kenya'],
            ['code' => 'KI', 'name_ja' => 'キリバス', 'name_en' => 'Kiribati'],
            ['code' => 'KP', 'name_ja' => '朝鮮民主主義人民共和国', 'name_en' => 'Korea (Democratic People\'s Republic of)'],
            ['code' => 'KR', 'name_ja' => '大韓民国', 'name_en' => 'Korea, Republic of'],
            ['code' => 'KW', 'name_ja' => 'クウェート', 'name_en' => 'Kuwait'],
            ['code' => 'KG', 'name_ja' => 'キルギス', 'name_en' => 'Kyrgyzstan'],
            ['code' => 'LA', 'name_ja' => 'ラオス人民民主共和国', 'name_en' => 'Lao People\'s Democratic Republic'],
            ['code' => 'LV', 'name_ja' => 'ラトビア', 'name_en' => 'Latvia'],
            ['code' => 'LB', 'name_ja' => 'レバノン', 'name_en' => 'Lebanon'],
            ['code' => 'LS', 'name_ja' => 'レソト', 'name_en' => 'Lesotho'],
            ['code' => 'LR', 'name_ja' => 'リベリア', 'name_en' => 'Liberia'],
            ['code' => 'LY', 'name_ja' => 'リビア', 'name_en' => 'Libya'],
            ['code' => 'LI', 'name_ja' => 'リヒテンシュタイン', 'name_en' => 'Liechtenstein'],
            ['code' => 'LT', 'name_ja' => 'リトアニア', 'name_en' => 'Lithuania'],
            ['code' => 'LU', 'name_ja' => 'ルクセンブルク', 'name_en' => 'Luxembourg'],
            ['code' => 'MO', 'name_ja' => 'マカオ', 'name_en' => 'Macao'],
            ['code' => 'MG', 'name_ja' => 'マダガスカル', 'name_en' => 'Madagascar'],
            ['code' => 'MW', 'name_ja' => 'マラウイ', 'name_en' => 'Malawi'],
            ['code' => 'MY', 'name_ja' => 'マレーシア', 'name_en' => 'Malaysia'],
            ['code' => 'MV', 'name_ja' => 'モルディブ', 'name_en' => 'Maldives'],
            ['code' => 'ML', 'name_ja' => 'マリ', 'name_en' => 'Mali'],
            ['code' => 'MT', 'name_ja' => 'マルタ', 'name_en' => 'Malta'],
            ['code' => 'MH', 'name_ja' => 'マーシャル諸島', 'name_en' => 'Marshall Islands'],
            ['code' => 'MQ', 'name_ja' => 'マルティニーク', 'name_en' => 'Martinique'],
            ['code' => 'MR', 'name_ja' => 'モーリタニア', 'name_en' => 'Mauritania'],
            ['code' => 'MU', 'name_ja' => 'モーリシャス', 'name_en' => 'Mauritius'],
            ['code' => 'YT', 'name_ja' => 'マヨット', 'name_en' => 'Mayotte'],
            ['code' => 'MX', 'name_ja' => 'メキシコ', 'name_en' => 'Mexico'],
            ['code' => 'FM', 'name_ja' => 'ミクロネシア連邦', 'name_en' => 'Micronesia (Federated States of)'],
            ['code' => 'MD', 'name_ja' => 'モルドバ共和国', 'name_en' => 'Moldova, Republic of'],
            ['code' => 'MC', 'name_ja' => 'モナコ', 'name_en' => 'Monaco'],
            ['code' => 'MN', 'name_ja' => 'モンゴル', 'name_en' => 'Mongolia'],
            ['code' => 'ME', 'name_ja' => 'モンテネグロ', 'name_en' => 'Montenegro'],
            ['code' => 'MS', 'name_ja' => 'モントセラト', 'name_en' => 'Montserrat'],
            ['code' => 'MA', 'name_ja' => 'モロッコ', 'name_en' => 'Morocco'],
            ['code' => 'MZ', 'name_ja' => 'モザンビーク', 'name_en' => 'Mozambique'],
            ['code' => 'MM', 'name_ja' => 'ミャンマー', 'name_en' => 'Myanmar'],
            ['code' => 'NA', 'name_ja' => 'ナミビア', 'name_en' => 'Namibia'],
            ['code' => 'NR', 'name_ja' => 'ナウル', 'name_en' => 'Nauru'],
            ['code' => 'NP', 'name_ja' => 'ネパール', 'name_en' => 'Nepal'],
            ['code' => 'NL', 'name_ja' => 'オランダ', 'name_en' => 'Netherlands'],
            ['code' => 'NC', 'name_ja' => 'ニューカレドニア', 'name_en' => 'New Caledonia'],
            ['code' => 'NZ', 'name_ja' => 'ニュージーランド', 'name_en' => 'New Zealand'],
            ['code' => 'NI', 'name_ja' => 'ニカラグア', 'name_en' => 'Nicaragua'],
            ['code' => 'NE', 'name_ja' => 'ニジェール', 'name_en' => 'Niger'],
            ['code' => 'NG', 'name_ja' => 'ナイジェリア', 'name_en' => 'Nigeria'],
            ['code' => 'NU', 'name_ja' => 'ニウエ', 'name_en' => 'Niue'],
            ['code' => 'NF', 'name_ja' => 'ノーフォーク島', 'name_en' => 'Norfolk Island'],
            ['code' => 'MK', 'name_ja' => '北マケドニア', 'name_en' => 'North Macedonia'],
            ['code' => 'MP', 'name_ja' => '北マリアナ諸島', 'name_en' => 'Northern Mariana Islands'],
            ['code' => 'NO', 'name_ja' => 'ノルウェー', 'name_en' => 'Norway'],
            ['code' => 'OM', 'name_ja' => 'オマーン', 'name_en' => 'Oman'],
            ['code' => 'PK', 'name_ja' => 'パキスタン', 'name_en' => 'Pakistan'],
            ['code' => 'PW', 'name_ja' => 'パラオ', 'name_en' => 'Palau'],
            ['code' => 'PS', 'name_ja' => 'パレスチナ', 'name_en' => 'Palestine, State of'],
            ['code' => 'PA', 'name_ja' => 'パナマ', 'name_en' => 'Panama'],
            ['code' => 'PG', 'name_ja' => 'パプアニューギニア', 'name_en' => 'Papua New Guinea'],
            ['code' => 'PY', 'name_ja' => 'パラグアイ', 'name_en' => 'Paraguay'],
            ['code' => 'PE', 'name_ja' => 'ペルー', 'name_en' => 'Peru'],
            ['code' => 'PH', 'name_ja' => 'フィリピン', 'name_en' => 'Philippines'],
            ['code' => 'PN', 'name_ja' => 'ピトケアン', 'name_en' => 'Pitcairn'],
            ['code' => 'PL', 'name_ja' => 'ポーランド', 'name_en' => 'Poland'],
            ['code' => 'PT', 'name_ja' => 'ポルトガル', 'name_en' => 'Portugal'],
            ['code' => 'PR', 'name_ja' => 'プエルトリコ', 'name_en' => 'Puerto Rico'],
            ['code' => 'QA', 'name_ja' => 'カタール', 'name_en' => 'Qatar'],
            ['code' => 'RE', 'name_ja' => 'レユニオン', 'name_en' => 'Réunion'],
            ['code' => 'RO', 'name_ja' => 'ルーマニア', 'name_en' => 'Romania'],
            ['code' => 'RU', 'name_ja' => 'ロシア連邦', 'name_en' => 'Russian Federation'],
            ['code' => 'RW', 'name_ja' => 'ルワンダ', 'name_en' => 'Rwanda'],
            ['code' => 'BL', 'name_ja' => 'サン・バルテルミー', 'name_en' => 'Saint Barthélemy'],
            ['code' => 'SH', 'name_ja' => 'セントヘレナ・アセンションおよびトリスタンダクーニャ', 'name_en' => 'Saint Helena, Ascension and Tristan da Cunha'],
            ['code' => 'KN', 'name_ja' => 'セントクリストファー・ネイビス', 'name_en' => 'Saint Kitts and Nevis'],
            ['code' => 'LC', 'name_ja' => 'セントルシア', 'name_en' => 'Saint Lucia'],
            ['code' => 'MF', 'name_ja' => 'サン・マルタン（フランス領）', 'name_en' => 'Saint Martin (French part)'],
            ['code' => 'PM', 'name_ja' => 'サンピエール島・ミクロン島', 'name_en' => 'Saint Pierre and Miquelon'],
            ['code' => 'VC', 'name_ja' => 'セントビンセント及びグレナディーン諸島', 'name_en' => 'Saint Vincent and the Grenadines'],
            ['code' => 'WS', 'name_ja' => 'サモア', 'name_en' => 'Samoa'],
            ['code' => 'SM', 'name_ja' => 'サンマリノ', 'name_en' => 'San Marino'],
            ['code' => 'ST', 'name_ja' => 'サントメ・プリンシペ', 'name_en' => 'Sao Tome and Principe'],
            ['code' => 'SA', 'name_ja' => 'サウジアラビア', 'name_en' => 'Saudi Arabia'],
            ['code' => 'SN', 'name_ja' => 'セネガル', 'name_en' => 'Senegal'],
            ['code' => 'RS', 'name_ja' => 'セルビア', 'name_en' => 'Serbia'],
            ['code' => 'SC', 'name_ja' => 'セーシェル', 'name_en' => 'Seychelles'],
            ['code' => 'SL', 'name_ja' => 'シエラレオネ', 'name_en' => 'Sierra Leone'],
            ['code' => 'SG', 'name_ja' => 'シンガポール', 'name_en' => 'Singapore'],
            ['code' => 'SX', 'name_ja' => 'シント・マールテン（オランダ領）', 'name_en' => 'Sint Maarten (Dutch part)'],
            ['code' => 'SK', 'name_ja' => 'スロバキア', 'name_en' => 'Slovakia'],
            ['code' => 'SI', 'name_ja' => 'スロベニア', 'name_en' => 'Slovenia'],
            ['code' => 'SB', 'name_ja' => 'ソロモン諸島', 'name_en' => 'Solomon Islands'],
            ['code' => 'SO', 'name_ja' => 'ソマリア', 'name_en' => 'Somalia'],
            ['code' => 'ZA', 'name_ja' => '南アフリカ', 'name_en' => 'South Africa'],
            ['code' => 'GS', 'name_ja' => 'サウスジョージア・サウスサンドウィッチ諸島', 'name_en' => 'South Georgia and the South Sandwich Islands'],
            ['code' => 'SS', 'name_ja' => '南スーダン', 'name_en' => 'South Sudan'],
            ['code' => 'ES', 'name_ja' => 'スペイン', 'name_en' => 'Spain'],
            ['code' => 'LK', 'name_ja' => 'スリランカ', 'name_en' => 'Sri Lanka'],
            ['code' => 'SD', 'name_ja' => 'スーダン', 'name_en' => 'Sudan'],
            ['code' => 'SR', 'name_ja' => 'スリナム', 'name_en' => 'Suriname'],
            ['code' => 'SJ', 'name_ja' => 'スバールバル諸島およびヤンマイエン島', 'name_en' => 'Svalbard and Jan Mayen'],
            ['code' => 'SE', 'name_ja' => 'スウェーデン', 'name_en' => 'Sweden'],
            ['code' => 'CH', 'name_ja' => 'スイス', 'name_en' => 'Switzerland'],
            ['code' => 'SY', 'name_ja' => 'シリア・アラブ共和国', 'name_en' => 'Syrian Arab Republic'],
            ['code' => 'TW', 'name_ja' => '台湾（中国の省）', 'name_en' => 'Taiwan, Province of China'],
            ['code' => 'TJ', 'name_ja' => 'タジキスタン', 'name_en' => 'Tajikistan'],
            ['code' => 'TZ', 'name_ja' => 'タンザニア連合共和国', 'name_en' => 'Tanzania, United Republic of'],
            ['code' => 'TH', 'name_ja' => 'タイ', 'name_en' => 'Thailand'],
            ['code' => 'TL', 'name_ja' => '東ティモール', 'name_en' => 'Timor-Leste'],
            ['code' => 'TG', 'name_ja' => 'トーゴ', 'name_en' => 'Togo'],
            ['code' => 'TK', 'name_ja' => 'トケラウ', 'name_en' => 'Tokelau'],
            ['code' => 'TO', 'name_ja' => 'トンガ', 'name_en' => 'Tonga'],
            ['code' => 'TT', 'name_ja' => 'トリニダード・トバゴ', 'name_en' => 'Trinidad and Tobago'],
            ['code' => 'TN', 'name_ja' => 'チュニジア', 'name_en' => 'Tunisia'],
            ['code' => 'TR', 'name_ja' => 'トルコ', 'name_en' => 'Turkey'],
            ['code' => 'TM', 'name_ja' => 'トルクメニスタン', 'name_en' => 'Turkmenistan'],
            ['code' => 'TC', 'name_ja' => 'タークス・カイコス諸島', 'name_en' => 'Turks and Caicos Islands'],
            ['code' => 'TV', 'name_ja' => 'ツバル', 'name_en' => 'Tuvalu'],
            ['code' => 'UG', 'name_ja' => 'ウガンダ', 'name_en' => 'Uganda'],
            ['code' => 'UA', 'name_ja' => 'ウクライナ', 'name_en' => 'Ukraine'],
            ['code' => 'AE', 'name_ja' => 'アラブ首長国連邦', 'name_en' => 'United Arab Emirates'],
            ['code' => 'GB', 'name_ja' => 'イギリス', 'name_en' => 'United Kingdom of Great Britain and Northern Ireland'],
            ['code' => 'US', 'name_ja' => 'アメリカ合衆国', 'name_en' => 'United States of America'],
            ['code' => 'UM', 'name_ja' => '合衆国領有小離島', 'name_en' => 'United States Minor Outlying Islands'],
            ['code' => 'UY', 'name_ja' => 'ウルグアイ', 'name_en' => 'Uruguay'],
            ['code' => 'UZ', 'name_ja' => 'ウズベキスタン', 'name_en' => 'Uzbekistan'],
            ['code' => 'VU', 'name_ja' => 'バヌアツ', 'name_en' => 'Vanuatu'],
            ['code' => 'VE', 'name_ja' => 'ベネズエラ・ボリバル共和国', 'name_en' => 'Venezuela (Bolivarian Republic of)'],
            ['code' => 'VN', 'name_ja' => 'ベトナム', 'name_en' => 'Viet Nam'],
            ['code' => 'VG', 'name_ja' => 'イギリス領ヴァージン諸島', 'name_en' => 'Virgin Islands (British)'],
            ['code' => 'VI', 'name_ja' => 'アメリカ領ヴァージン諸島', 'name_en' => 'Virgin Islands (U.S.)'],
            ['code' => 'WF', 'name_ja' => 'ウォリス・フツナ', 'name_en' => 'Wallis and Futuna'],
            ['code' => 'EH', 'name_ja' => '西サハラ', 'name_en' => 'Western Sahara'],
            ['code' => 'YE', 'name_ja' => 'イエメン', 'name_en' => 'Yemen'],
            ['code' => 'ZM', 'name_ja' => 'ザンビア', 'name_en' => 'Zambia'],
            ['code' => 'ZW', 'name_ja' => 'ジンバブエ', 'name_en' => 'Zimbabwe']
        ];

        foreach ($countries as $country) {
            DB::table('countries')->insert([
                'name_ja' => $country['name_ja'],
                'name_en' => $country['name_en'],
                'code' => $country['code'],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
        }
    }
}