<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class CountriesTableSeeder extends Seeder
{
    public function run(): void
    {
        // 既存のデータを削除（PostgreSQL用、外部キー制約も考慮してCASCADEで削除）
        DB::statement('TRUNCATE TABLE countries RESTART IDENTITY CASCADE;');

        $countries = [
            ['code' => 'AF', 'name_ja' => 'アフガニスタン', 'name_en' => 'Afghanistan', 'name_ja_hiragana' => 'あふがにすたん'],
            ['code' => 'AX', 'name_ja' => 'オーランド諸島', 'name_en' => 'Åland Islands', 'name_ja_hiragana' => 'おーらんどしょとう'],
            ['code' => 'AL', 'name_ja' => 'アルバニア', 'name_en' => 'Albania', 'name_ja_hiragana' => 'あるばにあ'],
            ['code' => 'DZ', 'name_ja' => 'アルジェリア', 'name_en' => 'Algeria', 'name_ja_hiragana' => 'あるじぇりあ'],
            ['code' => 'AS', 'name_ja' => 'アメリカ領サモア', 'name_en' => 'American Samoa', 'name_ja_hiragana' => 'あめりかりょうさもあ'],
            ['code' => 'AD', 'name_ja' => 'アンドラ', 'name_en' => 'Andorra', 'name_ja_hiragana' => 'あんどら'],
            ['code' => 'AO', 'name_ja' => 'アンゴラ', 'name_en' => 'Angola', 'name_ja_hiragana' => 'あんごら'],
            ['code' => 'AI', 'name_ja' => 'アンギラ', 'name_en' => 'Anguilla', 'name_ja_hiragana' => 'あんぎら'],
            ['code' => 'AQ', 'name_ja' => '南極', 'name_en' => 'Antarctica', 'name_ja_hiragana' => 'なんきょく'],
            ['code' => 'AG', 'name_ja' => 'アンティグア・バーブーダ', 'name_en' => 'Antigua and Barbuda', 'name_ja_hiragana' => 'あんてぃぐあばーぶーだ'],
            ['code' => 'AR', 'name_ja' => 'アルゼンチン', 'name_en' => 'Argentina', 'name_ja_hiragana' => 'あるぜんちん'],
            ['code' => 'AM', 'name_ja' => 'アルメニア', 'name_en' => 'Armenia', 'name_ja_hiragana' => 'あるめにあ'],
            ['code' => 'AW', 'name_ja' => 'アルバ', 'name_en' => 'Aruba', 'name_ja_hiragana' => 'あるば'],
            ['code' => 'AU', 'name_ja' => 'オーストラリア', 'name_en' => 'Australia', 'name_ja_hiragana' => 'おーすとらりあ'],
            ['code' => 'AT', 'name_ja' => 'オーストリア', 'name_en' => 'Austria', 'name_ja_hiragana' => 'おーすとりあ'],
            ['code' => 'AZ', 'name_ja' => 'アゼルバイジャン', 'name_en' => 'Azerbaijan', 'name_ja_hiragana' => 'あぜるばいじゃん'],
            ['code' => 'BS', 'name_ja' => 'バハマ', 'name_en' => 'Bahamas', 'name_ja_hiragana' => 'ばはま'],
            ['code' => 'BH', 'name_ja' => 'バーレーン', 'name_en' => 'Bahrain', 'name_ja_hiragana' => 'ばーれーん'],
            ['code' => 'BD', 'name_ja' => 'バングラデシュ', 'name_en' => 'Bangladesh', 'name_ja_hiragana' => 'ばんぐらでしゅ'],
            ['code' => 'BB', 'name_ja' => 'バルバドス', 'name_en' => 'Barbados', 'name_ja_hiragana' => 'ばるばどす'],
            ['code' => 'BY', 'name_ja' => 'ベラルーシ', 'name_en' => 'Belarus', 'name_ja_hiragana' => 'べらるーし'],
            ['code' => 'BE', 'name_ja' => 'ベルギー', 'name_en' => 'Belgium', 'name_ja_hiragana' => 'べるぎー'],
            ['code' => 'BZ', 'name_ja' => 'ベリーズ', 'name_en' => 'Belize', 'name_ja_hiragana' => 'べりーず'],
            ['code' => 'BJ', 'name_ja' => 'ベナン', 'name_en' => 'Benin', 'name_ja_hiragana' => 'べなん'],
            ['code' => 'BM', 'name_ja' => 'バミューダ', 'name_en' => 'Bermuda', 'name_ja_hiragana' => 'ばみゅーだ'],
            ['code' => 'BT', 'name_ja' => 'ブータン', 'name_en' => 'Bhutan', 'name_ja_hiragana' => 'ぶーたん'],
            ['code' => 'BO', 'name_ja' => 'ボリビア多民族国', 'name_en' => 'Bolivia (Plurinational State of)', 'name_ja_hiragana' => 'ぼりびあたみんぞくこく'],
            ['code' => 'BQ', 'name_ja' => 'ボネール、シント・ユースタティウスおよびサバ', 'name_en' => 'Bonaire, Sint Eustatius and Saba', 'name_ja_hiragana' => 'ぼねーるしんとゆーすたてぃうすおよびさば'],
            ['code' => 'BA', 'name_ja' => 'ボスニア・ヘルツェゴビナ', 'name_en' => 'Bosnia and Herzegovina', 'name_ja_hiragana' => 'ぼすにあへるつぇごびな'],
            ['code' => 'BW', 'name_ja' => 'ボツワナ', 'name_en' => 'Botswana', 'name_ja_hiragana' => 'ぼつわな'],
            ['code' => 'BV', 'name_ja' => 'ブーベ島', 'name_en' => 'Bouvet Island', 'name_ja_hiragana' => 'ぶーべとう'],
            ['code' => 'BR', 'name_ja' => 'ブラジル', 'name_en' => 'Brazil', 'name_ja_hiragana' => 'ぶらじる'],
            ['code' => 'IO', 'name_ja' => 'イギリス領インド洋地域', 'name_en' => 'British Indian Ocean Territory', 'name_ja_hiragana' => 'いぎりすりょういんどようちいき'],
            ['code' => 'BN', 'name_ja' => 'ブルネイ・ダルサラーム', 'name_en' => 'Brunei Darussalam', 'name_ja_hiragana' => 'ぶるねいだるさらーむ'],
            ['code' => 'BG', 'name_ja' => 'ブルガリア', 'name_en' => 'Bulgaria', 'name_ja_hiragana' => 'ぶるがりあ'],
            ['code' => 'BF', 'name_ja' => 'ブルキナファソ', 'name_en' => 'Burkina Faso', 'name_ja_hiragana' => 'ぶるきなふぁそ'],
            ['code' => 'BI', 'name_ja' => 'ブルンジ', 'name_en' => 'Burundi', 'name_ja_hiragana' => 'ぶるんじ'],
            ['code' => 'CV', 'name_ja' => 'カーボベルデ', 'name_en' => 'Cabo Verde', 'name_ja_hiragana' => 'かーぼべるで'],
            ['code' => 'KH', 'name_ja' => 'カンボジア', 'name_en' => 'Cambodia', 'name_ja_hiragana' => 'かんぼじあ'],
            ['code' => 'CM', 'name_ja' => 'カメルーン', 'name_en' => 'Cameroon', 'name_ja_hiragana' => 'かめるーん'],
            ['code' => 'CA', 'name_ja' => 'カナダ', 'name_en' => 'Canada', 'name_ja_hiragana' => 'かなだ'],
            ['code' => 'KY', 'name_ja' => 'ケイマン諸島', 'name_en' => 'Cayman Islands', 'name_ja_hiragana' => 'けいまんしょとう'],
            ['code' => 'CF', 'name_ja' => '中央アフリカ共和国', 'name_en' => 'Central African Republic', 'name_ja_hiragana' => 'ちゅうおうあふりかきょうわこく'],
            ['code' => 'TD', 'name_ja' => 'チャド', 'name_en' => 'Chad', 'name_ja_hiragana' => 'ちゃど'],
            ['code' => 'CL', 'name_ja' => 'チリ', 'name_en' => 'Chile', 'name_ja_hiragana' => 'ちり'],
            ['code' => 'CN', 'name_ja' => '中国', 'name_en' => 'China', 'name_ja_hiragana' => 'ちゅうごく'],
            ['code' => 'CX', 'name_ja' => 'クリスマス島', 'name_en' => 'Christmas Island', 'name_ja_hiragana' => 'くりすますとう'],
            ['code' => 'CC', 'name_ja' => 'ココス(キーリング)諸島', 'name_en' => 'Cocos (Keeling) Islands', 'name_ja_hiragana' => 'ここすきーりんぐしょとう'],
            ['code' => 'CO', 'name_ja' => 'コロンビア', 'name_en' => 'Colombia', 'name_ja_hiragana' => 'ころんびあ'],
            ['code' => 'KM', 'name_ja' => 'コモロ', 'name_en' => 'Comoros', 'name_ja_hiragana' => 'こもろ'],
            ['code' => 'CG', 'name_ja' => 'コンゴ共和国', 'name_en' => 'Congo', 'name_ja_hiragana' => 'こんごきょうわこく'],
            ['code' => 'CD', 'name_ja' => 'コンゴ民主共和国', 'name_en' => 'Congo, Democratic Republic of the', 'name_ja_hiragana' => 'こんごみんしゅきょうわこく'],
            ['code' => 'CK', 'name_ja' => 'クック諸島', 'name_en' => 'Cook Islands', 'name_ja_hiragana' => 'くっくしょとう'],
            ['code' => 'CR', 'name_ja' => 'コスタリカ', 'name_en' => 'Costa Rica', 'name_ja_hiragana' => 'こすたりか'],
            ['code' => 'CI', 'name_ja' => 'コートジボワール', 'name_en' => 'Côte d\'Ivoire', 'name_ja_hiragana' => 'こーとじぼわーる'],
            ['code' => 'HR', 'name_ja' => 'クロアチア', 'name_en' => 'Croatia', 'name_ja_hiragana' => 'くろあちあ'],
            ['code' => 'CU', 'name_ja' => 'キューバ', 'name_en' => 'Cuba', 'name_ja_hiragana' => 'きゅーば'],
            ['code' => 'CW', 'name_ja' => 'キュラソー', 'name_en' => 'Curaçao', 'name_ja_hiragana' => 'きゅらそー'],
            ['code' => 'CY', 'name_ja' => 'キプロス', 'name_en' => 'Cyprus', 'name_ja_hiragana' => 'きぷろす'],
            ['code' => 'CZ', 'name_ja' => 'チェコ', 'name_en' => 'Czechia', 'name_ja_hiragana' => 'ちぇこ'],
            ['code' => 'DK', 'name_ja' => 'デンマーク', 'name_en' => 'Denmark', 'name_ja_hiragana' => 'でんまーく'],
            ['code' => 'DJ', 'name_ja' => 'ジブチ', 'name_en' => 'Djibouti', 'name_ja_hiragana' => 'じぶち'],
            ['code' => 'DM', 'name_ja' => 'ドミニカ国', 'name_en' => 'Dominica', 'name_ja_hiragana' => 'どみにかこく'],
            ['code' => 'DO', 'name_ja' => 'ドミニカ共和国', 'name_en' => 'Dominican Republic', 'name_ja_hiragana' => 'どみにかきょうわこく'],
            ['code' => 'EC', 'name_ja' => 'エクアドル', 'name_en' => 'Ecuador', 'name_ja_hiragana' => 'えくあどる'],
            ['code' => 'EG', 'name_ja' => 'エジプト', 'name_en' => 'Egypt', 'name_ja_hiragana' => 'えじぷと'],
            ['code' => 'SV', 'name_ja' => 'エルサルバドル', 'name_en' => 'El Salvador', 'name_ja_hiragana' => 'えるさるばどる'],
            ['code' => 'GQ', 'name_ja' => '赤道ギニア', 'name_en' => 'Equatorial Guinea', 'name_ja_hiragana' => 'せきどうぎにあ'],
            ['code' => 'ER', 'name_ja' => 'エリトリア', 'name_en' => 'Eritrea', 'name_ja_hiragana' => 'えりとりあ'],
            ['code' => 'EE', 'name_ja' => 'エストニア', 'name_en' => 'Estonia', 'name_ja_hiragana' => 'えすとにあ'],
            ['code' => 'SZ', 'name_ja' => 'エスワティニ', 'name_en' => 'Eswatini', 'name_ja_hiragana' => 'えすわてぃに'],
            ['code' => 'ET', 'name_ja' => 'エチオピア', 'name_en' => 'Ethiopia', 'name_ja_hiragana' => 'えちおぴあ'],
            ['code' => 'FK', 'name_ja' => 'フォークランド諸島(マルビナス諸島)', 'name_en' => 'Falkland Islands (Malvinas)', 'name_ja_hiragana' => 'ふぉーくらんどしょとうまるびなすしょとう'],
            ['code' => 'FO', 'name_ja' => 'フェロー諸島', 'name_en' => 'Faroe Islands', 'name_ja_hiragana' => 'ふぇろーしょとう'],
            ['code' => 'FJ', 'name_ja' => 'フィジー', 'name_en' => 'Fiji', 'name_ja_hiragana' => 'ふぃじー'],
            ['code' => 'FI', 'name_ja' => 'フィンランド', 'name_en' => 'Finland', 'name_ja_hiragana' => 'ふぃんらんど'],
            ['code' => 'FR', 'name_ja' => 'フランス', 'name_en' => 'France', 'name_ja_hiragana' => 'ふらんす'],
            ['code' => 'GF', 'name_ja' => 'フランス領ギアナ', 'name_en' => 'French Guiana', 'name_ja_hiragana' => 'ふらんすりょうぎあな'],
            ['code' => 'PF', 'name_ja' => 'フランス領ポリネシア', 'name_en' => 'French Polynesia', 'name_ja_hiragana' => 'ふらんすりょうぽりねしあ'],
            ['code' => 'TF', 'name_ja' => 'フランス領南方・南極地域', 'name_en' => 'French Southern Territories', 'name_ja_hiragana' => 'ふらんすりょうなんぽうなんきょくちいき'],
            ['code' => 'GA', 'name_ja' => 'ガボン', 'name_en' => 'Gabon', 'name_ja_hiragana' => 'がぼん'],
            ['code' => 'GM', 'name_ja' => 'ガンビア', 'name_en' => 'Gambia', 'name_ja_hiragana' => 'がんびあ'],
            ['code' => 'GE', 'name_ja' => 'ジョージア', 'name_en' => 'Georgia', 'name_ja_hiragana' => 'じょーじあ'],
            ['code' => 'DE', 'name_ja' => 'ドイツ', 'name_en' => 'Germany', 'name_ja_hiragana' => 'どいつ'],
            ['code' => 'GH', 'name_ja' => 'ガーナ', 'name_en' => 'Ghana', 'name_ja_hiragana' => 'がーな'],
            ['code' => 'GI', 'name_ja' => 'ジブラルタル', 'name_en' => 'Gibraltar', 'name_ja_hiragana' => 'じぶらるたる'],
            ['code' => 'GR', 'name_ja' => 'ギリシャ', 'name_en' => 'Greece', 'name_ja_hiragana' => 'ぎりしゃ'],
            ['code' => 'GL', 'name_ja' => 'グリーンランド', 'name_en' => 'Greenland', 'name_ja_hiragana' => 'ぐりーんらんど'],
            ['code' => 'GD', 'name_ja' => 'グレナダ', 'name_en' => 'Grenada', 'name_ja_hiragana' => 'ぐれなだ'],
            ['code' => 'GP', 'name_ja' => 'グアドループ', 'name_en' => 'Guadeloupe', 'name_ja_hiragana' => 'ぐあどるーぷ'],
            ['code' => 'GU', 'name_ja' => 'グアム', 'name_en' => 'Guam', 'name_ja_hiragana' => 'ぐあむ'],
            ['code' => 'GT', 'name_ja' => 'グアテマラ', 'name_en' => 'Guatemala', 'name_ja_hiragana' => 'ぐあてまら'],
            ['code' => 'GG', 'name_ja' => 'ガーンジー', 'name_en' => 'Guernsey', 'name_ja_hiragana' => 'がーんじー'],
            ['code' => 'GN', 'name_ja' => 'ギニア', 'name_en' => 'Guinea', 'name_ja_hiragana' => 'ぎにあ'],
            ['code' => 'GW', 'name_ja' => 'ギニアビサウ', 'name_en' => 'Guinea-Bissau', 'name_ja_hiragana' => 'ぎにあびさう'],
            ['code' => 'GY', 'name_ja' => 'ガイアナ', 'name_en' => 'Guyana', 'name_ja_hiragana' => 'がいあな'],
            ['code' => 'HT', 'name_ja' => 'ハイチ', 'name_en' => 'Haiti', 'name_ja_hiragana' => 'はいち'],
            ['code' => 'HM', 'name_ja' => 'ハード島とマクドナルド諸島', 'name_en' => 'Heard Island and McDonald Islands', 'name_ja_hiragana' => 'はーどとうとまくどなるどしょとう'],
            ['code' => 'VA', 'name_ja' => 'バチカン市国', 'name_en' => 'Holy See', 'name_ja_hiragana' => 'ばちかんしこく'],
            ['code' => 'HN', 'name_ja' => 'ホンジュラス', 'name_en' => 'Honduras', 'name_ja_hiragana' => 'ほんじゅらす'],
            ['code' => 'HK', 'name_ja' => '香港', 'name_en' => 'Hong Kong', 'name_ja_hiragana' => 'ほんこん'],
            ['code' => 'HU', 'name_ja' => 'ハンガリー', 'name_en' => 'Hungary', 'name_ja_hiragana' => 'はんがりー'],
            ['code' => 'IS', 'name_ja' => 'アイスランド', 'name_en' => 'Iceland', 'name_ja_hiragana' => 'あいすらんど'],
            ['code' => 'IN', 'name_ja' => 'インド', 'name_en' => 'India', 'name_ja_hiragana' => 'いんど'],
            ['code' => 'ID', 'name_ja' => 'インドネシア', 'name_en' => 'Indonesia', 'name_ja_hiragana' => 'いんどねしあ'],
            ['code' => 'IR', 'name_ja' => 'イラン・イスラム共和国', 'name_en' => 'Iran (Islamic Republic of)', 'name_ja_hiragana' => 'いらんいすらむきょうわこく'],
            ['code' => 'IQ', 'name_ja' => 'イラク', 'name_en' => 'Iraq', 'name_ja_hiragana' => 'いらく'],
            ['code' => 'IE', 'name_ja' => 'アイルランド', 'name_en' => 'Ireland', 'name_ja_hiragana' => 'あいるらんど'],
            ['code' => 'IM', 'name_ja' => 'マン島', 'name_en' => 'Isle of Man', 'name_ja_hiragana' => 'まんとう'],
            ['code' => 'IL', 'name_ja' => 'イスラエル', 'name_en' => 'Israel', 'name_ja_hiragana' => 'いすらえる'],
            ['code' => 'IT', 'name_ja' => 'イタリア', 'name_en' => 'Italy', 'name_ja_hiragana' => 'いたりあ'],
            ['code' => 'JM', 'name_ja' => 'ジャマイカ', 'name_en' => 'Jamaica', 'name_ja_hiragana' => 'じゃまいか'],
            ['code' => 'JP', 'name_ja' => '日本', 'name_en' => 'Japan', 'name_ja_hiragana' => 'にほん'],
            ['code' => 'JE', 'name_ja' => 'ジャージー', 'name_en' => 'Jersey', 'name_ja_hiragana' => 'じゃーじー'],
            ['code' => 'JO', 'name_ja' => 'ヨルダン', 'name_en' => 'Jordan', 'name_ja_hiragana' => 'よるだん'],
            ['code' => 'KZ', 'name_ja' => 'カザフスタン', 'name_en' => 'Kazakhstan', 'name_ja_hiragana' => 'かざふすたん'],
            ['code' => 'KE', 'name_ja' => 'ケニア', 'name_en' => 'Kenya', 'name_ja_hiragana' => 'けにあ'],
            ['code' => 'KI', 'name_ja' => 'キリバス', 'name_en' => 'Kiribati', 'name_ja_hiragana' => 'きりばす'],
            ['code' => 'KP', 'name_ja' => '朝鮮民主主義人民共和国', 'name_en' => 'Korea (Democratic People\'s Republic of)', 'name_ja_hiragana' => 'ちょうせんみんしゅしゅぎじんみんきょうわこく'],
            ['code' => 'KR', 'name_ja' => '大韓民国', 'name_en' => 'Korea, Republic of', 'name_ja_hiragana' => 'だいかんみんこく'],
            ['code' => 'KW', 'name_ja' => 'クウェート', 'name_en' => 'Kuwait', 'name_ja_hiragana' => 'くうぇーと'],
            ['code' => 'KG', 'name_ja' => 'キルギス', 'name_en' => 'Kyrgyzstan', 'name_ja_hiragana' => 'きるぎす'],
            ['code' => 'LA', 'name_ja' => 'ラオス人民民主共和国', 'name_en' => 'Lao People\'s Democratic Republic', 'name_ja_hiragana' => 'らおすじんみんみんしゅきょうわこく'],
            ['code' => 'LV', 'name_ja' => 'ラトビア', 'name_en' => 'Latvia', 'name_ja_hiragana' => 'らとびあ'],
            ['code' => 'LB', 'name_ja' => 'レバノン', 'name_en' => 'Lebanon', 'name_ja_hiragana' => 'ればのん'],
            ['code' => 'LS', 'name_ja' => 'レソト', 'name_en' => 'Lesotho', 'name_ja_hiragana' => 'れそと'],
            ['code' => 'LR', 'name_ja' => 'リベリア', 'name_en' => 'Liberia', 'name_ja_hiragana' => 'りべりあ'],
            ['code' => 'LY', 'name_ja' => 'リビア', 'name_en' => 'Libya', 'name_ja_hiragana' => 'りびあ'],
            ['code' => 'LI', 'name_ja' => 'リヒテンシュタイン', 'name_en' => 'Liechtenstein', 'name_ja_hiragana' => 'りひてんしゅたいん'],
            ['code' => 'LT', 'name_ja' => 'リトアニア', 'name_en' => 'Lithuania', 'name_ja_hiragana' => 'りとあにあ'],
            ['code' => 'LU', 'name_ja' => 'ルクセンブルク', 'name_en' => 'Luxembourg', 'name_ja_hiragana' => 'るくせんぶるく'],
            ['code' => 'MO', 'name_ja' => 'マカオ', 'name_en' => 'Macao', 'name_ja_hiragana' => 'まかお'],
            ['code' => 'MG', 'name_ja' => 'マダガスカル', 'name_en' => 'Madagascar', 'name_ja_hiragana' => 'まだがすかる'],
            ['code' => 'MW', 'name_ja' => 'マラウイ', 'name_en' => 'Malawi', 'name_ja_hiragana' => 'まらうい'],
            ['code' => 'MY', 'name_ja' => 'マレーシア', 'name_en' => 'Malaysia', 'name_ja_hiragana' => 'まれーしあ'],
            ['code' => 'MV', 'name_ja' => 'モルディブ', 'name_en' => 'Maldives', 'name_ja_hiragana' => 'もるでぃぶ'],
            ['code' => 'ML', 'name_ja' => 'マリ', 'name_en' => 'Mali', 'name_ja_hiragana' => 'まり'],
            ['code' => 'MT', 'name_ja' => 'マルタ', 'name_en' => 'Malta', 'name_ja_hiragana' => 'まるた'],
            ['code' => 'MH', 'name_ja' => 'マーシャル諸島', 'name_en' => 'Marshall Islands', 'name_ja_hiragana' => 'まーしゃるしょとう'],
            ['code' => 'MQ', 'name_ja' => 'マルティニーク', 'name_en' => 'Martinique', 'name_ja_hiragana' => 'まるてぃにーく'],
            ['code' => 'MR', 'name_ja' => 'モーリタニア', 'name_en' => 'Mauritania', 'name_ja_hiragana' => 'もーりたにあ'],
            ['code' => 'MU', 'name_ja' => 'モーリシャス', 'name_en' => 'Mauritius', 'name_ja_hiragana' => 'もーりしゃす'],
            ['code' => 'YT', 'name_ja' => 'マヨット', 'name_en' => 'Mayotte', 'name_ja_hiragana' => 'まよっと'],
            ['code' => 'MX', 'name_ja' => 'メキシコ', 'name_en' => 'Mexico', 'name_ja_hiragana' => 'めきしこ'],
            ['code' => 'FM', 'name_ja' => 'ミクロネシア連邦', 'name_en' => 'Micronesia (Federated States of)', 'name_ja_hiragana' => 'みくろねしあれんぽう'],
            ['code' => 'MD', 'name_ja' => 'モルドバ共和国', 'name_en' => 'Moldova, Republic of', 'name_ja_hiragana' => 'もるどばきょうわこく'],
            ['code' => 'MC', 'name_ja' => 'モナコ', 'name_en' => 'Monaco', 'name_ja_hiragana' => 'もなこ'],
            ['code' => 'MN', 'name_ja' => 'モンゴル', 'name_en' => 'Mongolia', 'name_ja_hiragana' => 'もんごる'],
            ['code' => 'ME', 'name_ja' => 'モンテネグロ', 'name_en' => 'Montenegro', 'name_ja_hiragana' => 'もんてねぐろ'],
            ['code' => 'MS', 'name_ja' => 'モントセラト', 'name_en' => 'Montserrat', 'name_ja_hiragana' => 'もんとせらと'],
            ['code' => 'MA', 'name_ja' => 'モロッコ', 'name_en' => 'Morocco', 'name_ja_hiragana' => 'もろっこ'],
            ['code' => 'MZ', 'name_ja' => 'モザンビーク', 'name_en' => 'Mozambique', 'name_ja_hiragana' => 'もざんびーく'],
            ['code' => 'MM', 'name_ja' => 'ミャンマー', 'name_en' => 'Myanmar', 'name_ja_hiragana' => 'みゃんまー'],
            ['code' => 'NA', 'name_ja' => 'ナミビア', 'name_en' => 'Namibia', 'name_ja_hiragana' => 'なみびあ'],
            ['code' => 'NR', 'name_ja' => 'ナウル', 'name_en' => 'Nauru', 'name_ja_hiragana' => 'なうる'],
            ['code' => 'NP', 'name_ja' => 'ネパール', 'name_en' => 'Nepal', 'name_ja_hiragana' => 'ねぱーる'],
            ['code' => 'NL', 'name_ja' => 'オランダ', 'name_en' => 'Netherlands', 'name_ja_hiragana' => 'おらんだ'],
            ['code' => 'NC', 'name_ja' => 'ニューカレドニア', 'name_en' => 'New Caledonia', 'name_ja_hiragana' => 'にゅーかれどにあ'],
            ['code' => 'NZ', 'name_ja' => 'ニュージーランド', 'name_en' => 'New Zealand', 'name_ja_hiragana' => 'にゅーじーらんど'],
            ['code' => 'NI', 'name_ja' => 'ニカラグア', 'name_en' => 'Nicaragua', 'name_ja_hiragana' => 'にからぐあ'],
            ['code' => 'NE', 'name_ja' => 'ニジェール', 'name_en' => 'Niger', 'name_ja_hiragana' => 'にじぇーる'],
            ['code' => 'NG', 'name_ja' => 'ナイジェリア', 'name_en' => 'Nigeria', 'name_ja_hiragana' => 'ないじぇりあ'],
            ['code' => 'NU', 'name_ja' => 'ニウエ', 'name_en' => 'Niue', 'name_ja_hiragana' => 'にうえ'],
            ['code' => 'NF', 'name_ja' => 'ノーフォーク島', 'name_en' => 'Norfolk Island', 'name_ja_hiragana' => 'のーふぉーくとう'],
            ['code' => 'MK', 'name_ja' => '北マケドニア', 'name_en' => 'North Macedonia', 'name_ja_hiragana' => 'きたまけどにあ'],
            ['code' => 'MP', 'name_ja' => '北マリアナ諸島', 'name_en' => 'Northern Mariana Islands', 'name_ja_hiragana' => 'きたまりあなしょとう'],
            ['code' => 'NO', 'name_ja' => 'ノルウェー', 'name_en' => 'Norway', 'name_ja_hiragana' => 'のるうぇー'],
            ['code' => 'OM', 'name_ja' => 'オマーン', 'name_en' => 'Oman', 'name_ja_hiragana' => 'おまーん'],
            ['code' => 'PK', 'name_ja' => 'パキスタン', 'name_en' => 'Pakistan', 'name_ja_hiragana' => 'ぱきすたん'],
            ['code' => 'PW', 'name_ja' => 'パラオ', 'name_en' => 'Palau', 'name_ja_hiragana' => 'ぱらお'],
            ['code' => 'PS', 'name_ja' => 'パレスチナ', 'name_en' => 'Palestine, State of', 'name_ja_hiragana' => 'ぱれすちな'],
            ['code' => 'PA', 'name_ja' => 'パナマ', 'name_en' => 'Panama', 'name_ja_hiragana' => 'ぱなま'],
            ['code' => 'PG', 'name_ja' => 'パプアニューギニア', 'name_en' => 'Papua New Guinea', 'name_ja_hiragana' => 'ぱぷあにゅーぎにあ'],
            ['code' => 'PY', 'name_ja' => 'パラグアイ', 'name_en' => 'Paraguay', 'name_ja_hiragana' => 'ぱらぐあい'],
            ['code' => 'PE', 'name_ja' => 'ペルー', 'name_en' => 'Peru', 'name_ja_hiragana' => 'ぺるー'],
            ['code' => 'PH', 'name_ja' => 'フィリピン', 'name_en' => 'Philippines', 'name_ja_hiragana' => 'ふぃりぴん'],
            ['code' => 'PN', 'name_ja' => 'ピトケアン', 'name_en' => 'Pitcairn', 'name_ja_hiragana' => 'ぴとけあん'],
            ['code' => 'PL', 'name_ja' => 'ポーランド', 'name_en' => 'Poland', 'name_ja_hiragana' => 'ぽーらんど'],
            ['code' => 'PT', 'name_ja' => 'ポルトガル', 'name_en' => 'Portugal', 'name_ja_hiragana' => 'ぽるとがる'],
            ['code' => 'PR', 'name_ja' => 'プエルトリコ', 'name_en' => 'Puerto Rico', 'name_ja_hiragana' => 'ぷえるとりこ'],
            ['code' => 'QA', 'name_ja' => 'カタール', 'name_en' => 'Qatar', 'name_ja_hiragana' => 'かたーる'],
            ['code' => 'RE', 'name_ja' => 'レユニオン', 'name_en' => 'Réunion', 'name_ja_hiragana' => 'れゆにおん'],
            ['code' => 'RO', 'name_ja' => 'ルーマニア', 'name_en' => 'Romania', 'name_ja_hiragana' => 'るーまにあ'],
            ['code' => 'RU', 'name_ja' => 'ロシア連邦', 'name_en' => 'Russian Federation', 'name_ja_hiragana' => 'ろしあれんぽう'],
            ['code' => 'RW', 'name_ja' => 'ルワンダ', 'name_en' => 'Rwanda', 'name_ja_hiragana' => 'るわんだ'],
            ['code' => 'BL', 'name_ja' => 'サン・バルテルミー', 'name_en' => 'Saint Barthélemy', 'name_ja_hiragana' => 'さんばるてるみー'],
            ['code' => 'SH', 'name_ja' => 'セントヘレナ・アセンションおよびトリスタンダクーニャ', 'name_en' => 'Saint Helena, Ascension and Tristan da Cunha', 'name_ja_hiragana' => 'せんとへれなあせんしょんおよびとりすたんだくーにゃ'],
            ['code' => 'KN', 'name_ja' => 'セントクリストファー・ネイビス', 'name_en' => 'Saint Kitts and Nevis', 'name_ja_hiragana' => 'せんとくりすとふぁーねいびす'],
            ['code' => 'LC', 'name_ja' => 'セントルシア', 'name_en' => 'Saint Lucia', 'name_ja_hiragana' => 'せんとるしあ'],
            ['code' => 'MF', 'name_ja' => 'サン・マルタン(フランス領)', 'name_en' => 'Saint Martin (French part)', 'name_ja_hiragana' => 'さんまるたんふらんすりょう'],
            ['code' => 'PM', 'name_ja' => 'サンピエール島・ミクロン島', 'name_en' => 'Saint Pierre and Miquelon', 'name_ja_hiragana' => 'さんぴえーるとうみくろんとう'],
            ['code' => 'VC', 'name_ja' => 'セントビンセント及びグレナディーン諸島', 'name_en' => 'Saint Vincent and the Grenadines', 'name_ja_hiragana' => 'せんとびんせんとおよびぐれなでぃーんしょとう'],
            ['code' => 'WS', 'name_ja' => 'サモア', 'name_en' => 'Samoa', 'name_ja_hiragana' => 'さもあ'],
            ['code' => 'SM', 'name_ja' => 'サンマリノ', 'name_en' => 'San Marino', 'name_ja_hiragana' => 'さんまりの'],
            ['code' => 'ST', 'name_ja' => 'サントメ・プリンシペ', 'name_en' => 'Sao Tome and Principe', 'name_ja_hiragana' => 'さんとめぷりんしぺ'],
            ['code' => 'SA', 'name_ja' => 'サウジアラビア', 'name_en' => 'Saudi Arabia', 'name_ja_hiragana' => 'さうじあらびあ'],
            ['code' => 'SN', 'name_ja' => 'セネガル', 'name_en' => 'Senegal', 'name_ja_hiragana' => 'せねがる'],
            ['code' => 'RS', 'name_ja' => 'セルビア', 'name_en' => 'Serbia', 'name_ja_hiragana' => 'せるびあ'],
            ['code' => 'SC', 'name_ja' => 'セーシェル', 'name_en' => 'Seychelles', 'name_ja_hiragana' => 'せーしぇる'],
            ['code' => 'SL', 'name_ja' => 'シエラレオネ', 'name_en' => 'Sierra Leone', 'name_ja_hiragana' => 'しえられおね'],
            ['code' => 'SG', 'name_ja' => 'シンガポール', 'name_en' => 'Singapore', 'name_ja_hiragana' => 'しんがぽーる'],
            ['code' => 'SX', 'name_ja' => 'シント・マールテン(オランダ領)', 'name_en' => 'Sint Maarten (Dutch part)', 'name_ja_hiragana' => 'しんとまーるてんおらんだりょう'],
            ['code' => 'SK', 'name_ja' => 'スロバキア', 'name_en' => 'Slovakia', 'name_ja_hiragana' => 'すろばきあ'],
            ['code' => 'SI', 'name_ja' => 'スロベニア', 'name_en' => 'Slovenia', 'name_ja_hiragana' => 'すろべにあ'],
            ['code' => 'SB', 'name_ja' => 'ソロモン諸島', 'name_en' => 'Solomon Islands', 'name_ja_hiragana' => 'そろもんしょとう'],
            ['code' => 'SO', 'name_ja' => 'ソマリア', 'name_en' => 'Somalia', 'name_ja_hiragana' => 'そまりあ'],
            ['code' => 'ZA', 'name_ja' => '南アフリカ', 'name_en' => 'South Africa', 'name_ja_hiragana' => 'みなみあふりか'],
            ['code' => 'GS', 'name_ja' => 'サウスジョージア・サウスサンドウィッチ諸島', 'name_en' => 'South Georgia and the South Sandwich Islands', 'name_ja_hiragana' => 'さうすじょーじあさうすさんどうぃっちしょとう'],
            ['code' => 'SS', 'name_ja' => '南スーダン', 'name_en' => 'South Sudan', 'name_ja_hiragana' => 'みなみすーだん'],
            ['code' => 'ES', 'name_ja' => 'スペイン', 'name_en' => 'Spain', 'name_ja_hiragana' => 'すぺいん'],
            ['code' => 'LK', 'name_ja' => 'スリランカ', 'name_en' => 'Sri Lanka', 'name_ja_hiragana' => 'すりらんか'],
            ['code' => 'SD', 'name_ja' => 'スーダン', 'name_en' => 'Sudan', 'name_ja_hiragana' => 'すーだん'],
            ['code' => 'SR', 'name_ja' => 'スリナム', 'name_en' => 'Suriname', 'name_ja_hiragana' => 'すりなむ'],
            ['code' => 'SJ', 'name_ja' => 'スバールバル諸島およびヤンマイエン島', 'name_en' => 'Svalbard and Jan Mayen', 'name_ja_hiragana' => 'すばーるばるしょとうおよびやんまいえんとう'],
            ['code' => 'SE', 'name_ja' => 'スウェーデン', 'name_en' => 'Sweden', 'name_ja_hiragana' => 'すうぇーでん'],
            ['code' => 'CH', 'name_ja' => 'スイス', 'name_en' => 'Switzerland', 'name_ja_hiragana' => 'すいす'],
            ['code' => 'SY', 'name_ja' => 'シリア・アラブ共和国', 'name_en' => 'Syrian Arab Republic', 'name_ja_hiragana' => 'しりああらぶきょうわこく'],
            ['code' => 'TW', 'name_ja' => '台湾(中国の省)', 'name_en' => 'Taiwan, Province of China', 'name_ja_hiragana' => 'たいわんちゅうごくのしょう'],
            ['code' => 'TJ', 'name_ja' => 'タジキスタン', 'name_en' => 'Tajikistan', 'name_ja_hiragana' => 'たじきすたん'],
            ['code' => 'TZ', 'name_ja' => 'タンザニア連合共和国', 'name_en' => 'Tanzania, United Republic of', 'name_ja_hiragana' => 'たんざにあれんごうきょうわこく'],
            ['code' => 'TH', 'name_ja' => 'タイ', 'name_en' => 'Thailand', 'name_ja_hiragana' => 'たい'],
            ['code' => 'TL', 'name_ja' => '東ティモール', 'name_en' => 'Timor-Leste', 'name_ja_hiragana' => 'ひがしてぃもーる'],
            ['code' => 'TG', 'name_ja' => 'トーゴ', 'name_en' => 'Togo', 'name_ja_hiragana' => 'とーご'],
            ['code' => 'TK', 'name_ja' => 'トケラウ', 'name_en' => 'Tokelau', 'name_ja_hiragana' => 'とけらう'],
            ['code' => 'TO', 'name_ja' => 'トンガ', 'name_en' => 'Tonga', 'name_ja_hiragana' => 'とんが'],
            ['code' => 'TT', 'name_ja' => 'トリニダード・トバゴ', 'name_en' => 'Trinidad and Tobago', 'name_ja_hiragana' => 'とりにだーどとばご'],
            ['code' => 'TN', 'name_ja' => 'チュニジア', 'name_en' => 'Tunisia', 'name_ja_hiragana' => 'ちゅにじあ'],
            ['code' => 'TR', 'name_ja' => 'トルコ', 'name_en' => 'Turkey', 'name_ja_hiragana' => 'とるこ'],
            ['code' => 'TM', 'name_ja' => 'トルクメニスタン', 'name_en' => 'Turkmenistan', 'name_ja_hiragana' => 'とるくめにすたん'],
            ['code' => 'TC', 'name_ja' => 'タークス・カイコス諸島', 'name_en' => 'Turks and Caicos Islands', 'name_ja_hiragana' => 'たーくすかいこすしょとう'],
            ['code' => 'TV', 'name_ja' => 'ツバル', 'name_en' => 'Tuvalu', 'name_ja_hiragana' => 'つばる'],
            ['code' => 'UG', 'name_ja' => 'ウガンダ', 'name_en' => 'Uganda', 'name_ja_hiragana' => 'うがんだ'],
            ['code' => 'UA', 'name_ja' => 'ウクライナ', 'name_en' => 'Ukraine', 'name_ja_hiragana' => 'うくらいな'],
            ['code' => 'AE', 'name_ja' => 'アラブ首長国連邦', 'name_en' => 'United Arab Emirates', 'name_ja_hiragana' => 'あらぶしゅちょうこくれんぽう'],
            ['code' => 'GB', 'name_ja' => 'イギリス', 'name_en' => 'United Kingdom of Great Britain and Northern Ireland', 'name_ja_hiragana' => 'いぎりす'],
            ['code' => 'US', 'name_ja' => 'アメリカ合衆国', 'name_en' => 'United States of America', 'name_ja_hiragana' => 'あめりかがっしゅうこく'],
            ['code' => 'UM', 'name_ja' => '合衆国領有小離島', 'name_en' => 'United States Minor Outlying Islands', 'name_ja_hiragana' => 'がっしゅうこくりょうゆうしょうりとう'],
            ['code' => 'UY', 'name_ja' => 'ウルグアイ', 'name_en' => 'Uruguay', 'name_ja_hiragana' => 'うるぐあい'],
            ['code' => 'UZ', 'name_ja' => 'ウズベキスタン', 'name_en' => 'Uzbekistan', 'name_ja_hiragana' => 'うずべきすたん'],
            ['code' => 'VU', 'name_ja' => 'バヌアツ', 'name_en' => 'Vanuatu', 'name_ja_hiragana' => 'ばぬあつ'],
            ['code' => 'VE', 'name_ja' => 'ベネズエラ・ボリバル共和国', 'name_en' => 'Venezuela (Bolivarian Republic of)', 'name_ja_hiragana' => 'べねずえらぼりばるきょうわこく'],
            ['code' => 'VN', 'name_ja' => 'ベトナム', 'name_en' => 'Viet Nam', 'name_ja_hiragana' => 'べとなむ'],
            ['code' => 'VG', 'name_ja' => 'イギリス領ヴァージン諸島', 'name_en' => 'Virgin Islands (British)', 'name_ja_hiragana' => 'いぎりすりょうゔぁーじんしょとう'],
            ['code' => 'VI', 'name_ja' => 'アメリカ領ヴァージン諸島', 'name_en' => 'Virgin Islands (U.S.)', 'name_ja_hiragana' => 'あめりかりょうゔぁーじんしょとう'],
            ['code' => 'WF', 'name_ja' => 'ウォリス・フツナ', 'name_en' => 'Wallis and Futuna', 'name_ja_hiragana' => 'うぉりすふつな'],
            ['code' => 'EH', 'name_ja' => '西サハラ', 'name_en' => 'Western Sahara', 'name_ja_hiragana' => 'にしさはら'],
            ['code' => 'YE', 'name_ja' => 'イエメン', 'name_en' => 'Yemen', 'name_ja_hiragana' => 'いえめん'],
            ['code' => 'ZM', 'name_ja' => 'ザンビア', 'name_en' => 'Zambia', 'name_ja_hiragana' => 'ざんびあ'],
            ['code' => 'ZW', 'name_ja' => 'ジンバブエ', 'name_en' => 'Zimbabwe', 'name_ja_hiragana' => 'じんばぶえ']
        ];

        foreach ($countries as $country) {
            DB::table('countries')->insert([
                'name_ja' => $country['name_ja'],
                'name_en' => $country['name_en'],
                'name_ja_hiragana' => $country['name_ja_hiragana'],
                'code' => $country['code'],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
        }
    }
}
